const data = {
  products: [
    {
      name: 'T-Shirt',
      slug: 't-shit',
      category: 'Shirts',
      price: 70,
      brand: 'Nike',
      image: '/images/shirt1.jpg',
      rating: 4.5,
      numReviews: 8,
      countInStock: 20,
      description: 'A popular shirt',
    },
    {
      name: 'Fit-Shirt',
      slug: 'Fit-shit',
      category: 'Shirts',
      price: 20,
      brand: 'Adidas',
      image: '/images/shirt2.jpg',
      rating: 3.2,
      numReviews: 10,
      countInStock: 20,
      description: 'A popular shirt',
    },
    {
      name: 'Slim-Shirt',
      slug: 'slim-shit',
      category: 'Shirts',
      image: '/images/shirt3.jpg',
      price: 89,
      brand: 'Raymond',
      rating: 3.8,
      numReviews: 20,
      countInStock: 5,
      description: 'A popular shirt',
    },
    {
      name: 'Golf-Pants',
      slug: 'golf-pants',
      category: 'Pants',
      price: 69,
      image: '/images/pants1.jpg',
      brand: 'oliver',
      rating: 4.1,
      numReviews: 30,
      countInStock: 55,
      description: 'A popular pants',
    },
    {
      name: 'Fit-Pants',
      slug: 'fit-pants',
      category: 'Pants',
      image: '/images/pants2.jpg',
      price: 105,
      brand: '3pcs',
      rating: 3.4,
      numReviews: 22,
      countInStock: 47,
      description: 'A popular pants',
    },
    {
      name: 'Formal-Pants',
      slug: 'formal-pants',
      category: 'Pants',
      image: '/images/pants3.jpg',
      price: 200,
      brand: 'nike',
      rating: 4.8,
      numReviews: 99,
      countInStock: 500,
      description: 'A popular pants',
    },
  ],
};

export default data;
